version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./CompagnieApplication:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root 
volumes:
    persistent:
